version: "3.0"
services:

  mongodb:
    image: mongo:5.0
    restart: always
    
    environment:
      MONGO_INITDB_ROOT_USERNAME: USERNAME
      MONGO_INITDB_ROOT_PASSWORD: PASSWORD
    ports:
      - 27018:27017
    volumes:
      - mongo_data:/data/db
    
  # /opt/keycloak/bin/kc.sh export --dir /opt/keycloak/data/import --users realm_file --realm myrealm
  keycloak:
    image: keycloak/keycloak:23.0
    command: -v start-dev --import-realm
    ports:
      - 8090:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./config:/opt/keycloak/data/import
  
  # gitlab:
  #   # pass: dune2024
  #   image: gitlab/gitlab-ee:latest
  #   restart: always
  #   ports:
  #     - '8091:80'
  #     - '443:443'
  #     - '2222:22'
  #   volumes:
  #     - './gitlab/config:/etc/gitlab'
  #     - './gitlab/logs:/var/log/gitlab'
  #     - './gitlab/data:/var/opt/gitlab'
  #   shm_size: '256m'
  #   # deploy:
  #     # resources:
  #       # limits:
  #         # cpus: '0.7' 
  #         # memory: 4096M

volumes:
  mongo_data:
